variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"
  DOCKER_IMAGE: kiko12122/picspace_kaloyan-s3cb06
  DOCKER_TAG: $CI_COMMIT_REF_SLUG

stages:
  - build
  - test
  - sonarqube-check
  - deploy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/libs

build:
  stage: build
  script:
    - ./gradlew assemble --parallel
  artifacts:
    paths:
      - build/libs/picspace-0.0.1-SNAPSHOT.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  image: gradle:8.2.0-jdk17-jammy
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: gradle sonarqube
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  only:
    - main
