version: '3'

services:
  app:
    build: .
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'picspace'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'ferarri320'
      MYSQL_ROOT_PASSWORD: 'ferarri320'
    ports:
      - "3306:3306"